version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:kinetic-ros-core
    command: roscore
    networks:
      - ros
    restart: always

  garry:
    image: ros:garry
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=garry"
    command: /entrypoint.sh
    networks:
      - ros
    restart: always
