name: garry
version: '0.1'
summary: A robot snail that will inevitably kill all humans
description: |
  Its not quite ready for that though.
  
grade: devel
confinement: devmode

parts:
  workspace:
    source: http://github.com/braineniac/garry.git
    source-branch: master
    source-space: ctr_arduino/
    plugin: catkin
    rosdistro: kinetic
    catkin-packages: [ctr_arduino]
  
apps:
  run:
    command: roslaunch ctr_arduino arduino.launch
