name: garry
version: '0.1'
summary: A robot snail that will inevitably kill all humans
description: |
  Its not quite ready for that though.
  
grade: devel
confinement: devmode

parts:
  workspace:
    source: http://github.com/braineniac/garry.git
    source-branch: devel
    plugin: catkin
    rosdistro: melodic
    catkin-packages: [garry]
  
apps:
  roscore:
    command: roscore
    plugs: [network, network-bind]
  
  roslaunch:
    command: roslaunch garry arduino.launch
    plugs: [network, network-bind]
